services:
  app:
    # build: .
    image: ghcr.io/tolegengca/mlidsai:latest
    network_mode: host

  cicflowmeter:
    image: ghcr.io/tshelter/cicflowmeter:latest
    network_mode: host
    command: "-v -i wlp1s0 -u http://localhost:8000/predict"

  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
