{
 "title": "mlidsai",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "2s,5s,10s,15s,30s,1m" }
  ]
 },
 "panels": [
  {
   "title": "Total bytes processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "increase(mlidsai_total_bytes_total[$interval])",
     "legendFormat": "bytes processed"
    }
   ]
  },
  {
   "title": "Total packets processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "increase(mlidsai_total_packets_total[$interval])",
     "legendFormat": "packets processed"
    }
   ]
  },
  {
   "title": "Total bytes per anomaly type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "increase(mlidsai_anomaly_type_bytes_total[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Packets per anomaly type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "increase(mlidsai_anomaly_type_packets_total[$interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total new sessions detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(mlidsai_total_sessions_total[$interval])",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Total anomaly sessions detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(mlidsai_anomaly_sessions_total[$interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}